### ISSUE TITLE
https://t.me/Yaytsogram_bot/Yaytsogram?startapp=invite2833921

### ISSUE THREAD

**Issue by Shummasmalik** [itsAPK/Telegram-Referral-Bot#10]
https://t.me/Yaytsogram_bot/Yaytsogram?startapp=invite2833921

**Comment by itsAPK** [comment]
Can u explain abt issue

**Comment by Shummasmalik** [comment]
t.me/Tomarket_ai_bot/app?startapp=r-0000z7al

**Comment by Shummasmalik** [comment]
t.me/Tomarket_ai_bot/app?startapp=r-0000z7al

**Comment by Shummasmalik** [comment]
t.me/Tomarket_ai_bot/app?startapp=r-0000z7al
